### ISSUE TITLE
"Export As" dialog does not export files

### ISSUE THREAD

**Issue by ForceVectorDestroy** [altlenny/openFVD#3]
The recent changes to the Mac code allow coaster files to be saved as .fvd files but attempting to export a track using any of the options available under the "Save As" dialog result in no files being created and thus no way to import a completed coaster into No Limits 2. 

The camera is also extremely shaky despite messing with my Mac preferences.

**Comment by geforcefan** [comment]
fixed in 4482a15b388f76158c0b189068be96b4a45c2509
